version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: stempl
      POSTGRES_PASSWORD: stempl_password
      POSTGRES_DB: stempl_db
    ports:
      - "5432:5432"
    volumes:
      - stempl_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stempl"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  stempl_db_data:
